spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
    data:
      mypay:
        jdbc-url: "jdbc:postgresql://\${MYPAY_DB_HOST}:5432/mypay"
        username: "\${MYPAY_DB_USER}"
        password: "\${MYPAY_DB_PASSWORD}"
        driverClassName: "org.postgresql.Driver"
management:
    endpoint:
      health:
        probes.enabled: true
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure.include: info, health
app:
