spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
    data:
      pu:
        jdbc-url: "jdbc:postgresql://\${PU_DB_HOST}:\${PU_DB_PORT:5432}/\${PU_DB_NAME:dbname}"
        username: "\${PU_DB_USER}"
        password: "\${PU_DB_PASSWORD}"
        driverClassName: "org.postgresql.Driver"
    temporal:
      connection:
        enable-https: "\${TEMPORAL_SERVER_ENABLE_HTTPS:false}"
        target: "\${TEMPORAL_SERVER_HOST:localhost}:\${TEMPORAL_SERVER_PORT:7233}"
        target.namespace: "\${TEMPORAL_SERVER_NAMESPACE:default}"

      # Listing workers and registered activities
      workers:
        - task-queue: PaymentsReportingIngestionWF
          name: PaymentsReportingIngestionWF
          activity-beans:
            - paymentsReportingIngestionFlowFileActivityImpl
            - sendEmailIngestionFlowActivityImpl
            - updateIngestionFlowStatusActivityImpl
        - task-queue: CreateDebtPositionSyncWF
          name: CreateDebtPositionSyncWF
          activity-beans:
            - sendDebtPositionIONotificationActivityImpl

management:
    endpoint:
      health:
        probes.enabled: true
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure.include: info, health


