spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
    data:
      pu:
        jdbc-url: "jdbc:postgresql://\${PU_DB_HOST}:\${PU_DB_PORT:5432}/\${PU_DB_NAME:dbname}"
        username: "\${PU_DB_USER}"
        password: "\${PU_DB_PASSWORD}"
        driverClassName: "org.postgresql.Driver"
    temporal:
      connection:
        enable-https: "\${TEMPORAL_SERVER_ENABLE_HTTPS:false}"
        target: "\${TEMPORAL_SERVER_HOST:localhost}:\${TEMPORAL_SERVER_PORT:7233}"
        target.namespace: "\${TEMPORAL_SERVER_NAMESPACE:default}"

      # Listing workers and registered activities
      workers:
        - task-queue: PaymentsReportingIngestionWF
          name: PaymentsReportingIngestionWF
          activity-beans:
            - paymentsReportingIngestionFlowFileActivityImpl
            - sendEmailIngestionFlowActivityImpl
            - updateIngestionFlowStatusActivityImpl
        - task-queue: CreateDebtPositionSyncWF
          name: CreateDebtPositionSyncWF
          activity-beans:
            - sendDebtPositionIONotificationActivityImpl

management:
    endpoint:
      health:
        probes.enabled: true
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure.include: info, health

springdoc:
  writer-with-default-pretty-printer: true

jwt:
  access-token:
    public-key: "\${JWT_TOKEN_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2ovm/rd3g69dq9PisinQ
                6mWy8ZttT8D+GKXCsHZycsGnN7b74TPyYy+4+h+9cgJeizp8RDRrufHjiBrqi/2r
                eOk/rD7ZHbpfQvHK8MYfgIVdtTxYMX/GGdOrX6/5TV2b8e2aCG6GmxF0UuEvxY9o
                TmcZUxnIeDtl/ixz4DQ754eS363qWfEA92opW+jcYzr07sbQtR86e+Z/s/CUeX6W
                1PHNvBqdlAgp2ecr/1DOLq1D9hEANBPSwbt+FM6FNe4vLphi7GTwiB0yaAuy+jE8
                odND6HPvvvmgbK1/2qTHn/HJjWUm11LUC73BszR32BKbdEEhxPQnnwswVekWzPi1
                IwIDAQAB
                -----END PUBLIC KEY-----}"
