server:
  http: "\${SERVER_PORT:8080}"

spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
    threads:
      virtual:
        enabled: "\${VIRTUAL_THREADS_ENABLED:true}"
    data:
      pu:
        jdbc-url: "jdbc:postgresql://\${PU_DB_HOST}:\${PU_DB_PORT:5432}/\${PU_DB_NAME:dbname}"
        username: "\${PU_DB_USER}"
        password: "\${PU_DB_PASSWORD}"
        driverClassName: "org.postgresql.Driver"
    temporal:
      connection:
        enable-https: "\${TEMPORAL_SERVER_ENABLE_HTTPS:false}"
        target: "\${TEMPORAL_SERVER_HOST:localhost}:\${TEMPORAL_SERVER_PORT:7233}"
        target.namespace: "\${TEMPORAL_SERVER_NAMESPACE:default}"

      # Listing workers and registered activities
      workers:
        - task-queue: IufClassificationWF
          name: IufClassificationWF
          activity-beans:
            - clearClassifyIufActivityImpl
            - iufClassificationActivityImpl
        - task-queue: TreasuryOpiIngestionWF
          name: TreasuryOpiIngestionWF
          activity-beans:
            - treasuryOpiIngestionActivityImpl
            - sendEmailIngestionFlowActivityImpl
            - updateIngestionFlowStatusActivityImpl
        - task-queue: PaymentsReportingIngestionWF
          name: PaymentsReportingIngestionWF
          activity-beans:
            - paymentsReportingIngestionFlowFileActivityImpl
            - sendEmailIngestionFlowActivityImpl
            - updateIngestionFlowStatusActivityImpl
        - task-queue: CreateDebtPositionSyncWF
          name: CreateDebtPositionSyncWF
          activity-beans:
            - sendDebtPositionIONotificationActivityImpl
        - task-queue: SynchronizeSyncAcaWF
          name: SynchronizeSyncAcaWF
          activity-beans:
            - synchronizeInstallmentAcaActivityImpl
            - finalizeDebtPositionSyncStatusActivityImpl
            - sendDebtPositionIONotificationActivityImpl
        - task-queue: TransferClassificationWF
          name: TransferClassificationWF
          activity-beans:
            - transferClassificationActivityImpl

management:
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure:
          include: health, info, prometheus, metrics
        base-path: /actuator
    endpoint:
      health:
        probes.enabled: true
        logging.slow-indicator-threshold: "\${HEALTH_ACTUATOR_LOGGER_TIMEOUT_DURATION:PT1S}"
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
      prometheus:
        enabled: true
    metrics:
      tags:
        application: ${artifactId}
      export:
        prometheus:
          enabled: true
          step: 1m
          descriptions: true
      enable:
        jvm: true
        process: true
        system: true
        http: true
        logback: true

springdoc:
  writer-with-default-pretty-printer: true

logging:
  level:
    root: "\${LOG_LEVEL_ROOT:INFO}"
    it.gov.pagopa: "\${LOG_LEVEL_PAGOPA:INFO}"
    org.springframework: "\${LOG_LEVEL_SPRING:INFO}"
    org.springframework.boot.availability: "\${LOG_LEVEL_SPRING_BOOT_AVAILABILITY:DEBUG}"

jwt:
  access-token:
    public-key: "\${JWT_TOKEN_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2ovm/rd3g69dq9PisinQ
                6mWy8ZttT8D+GKXCsHZycsGnN7b74TPyYy+4+h+9cgJeizp8RDRrufHjiBrqi/2r
                eOk/rD7ZHbpfQvHK8MYfgIVdtTxYMX/GGdOrX6/5TV2b8e2aCG6GmxF0UuEvxY9o
                TmcZUxnIeDtl/ixz4DQ754eS363qWfEA92opW+jcYzr07sbQtR86e+Z/s/CUeX6W
                1PHNvBqdlAgp2ecr/1DOLq1D9hEANBPSwbt+FM6FNe4vLphi7GTwiB0yaAuy+jE8
                odND6HPvvvmgbK1/2qTHn/HJjWUm11LUC73BszR32BKbdEEhxPQnnwswVekWzPi1
                IwIDAQAB
                -----END PUBLIC KEY-----}"
