name: 🚀 Payments release

on:
  push:
    branches:
      - develop
      - uat
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'
  workflow_dispatch:

jobs:
  payments-flow-release:
    runs-on: ubuntu-22.04
    steps:
      - name: 🔖 Checkout code
        # https://github.com/actions/checkout/releases/tag/v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.ref_name }}

      - name: 🚀 release + docker + azdo
        # https://github.com/pagopa/github-actions-template/releases/tag/v1.19.2
        uses: pagopa/github-actions-template/payments-flow-release@922ed4e43b0e45a5e47eb0296d550996d8c87c64
        with:
          current_branch: ${{ github.ref_name }}
