name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    steps:

      - name: 🚀 Release with docker action
        id: release
        uses: pagopa/eng-github-actions-iac-template/global/release-with-docker@main #
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
